/**
 * Generates src/styles/skins.css from scripts/skin-palettes.mjs.
 *
 *   node scripts/build-skins.mjs          # write the CSS
 *   node scripts/build-skins.mjs --check  # contrast report only, no write
 *
 * Why a generator: the app's Tailwind wiring is `hsl(var(--token))`, so every
 * token has to be a solid "H S% L%" triplet for Tailwind to apply its own
 * alpha. The imported designs express borders and soft fills as rgba over a
 * known ground, so those get composited here rather than eyeballed.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { SKINS, CAT_HUES } from "./skin-palettes.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../src/styles/skins.css");

/* ── colour maths ─────────────────────────────────────────────────────── */

function parseHex(hex) {
  let h = hex.replace("#", "").trim();
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

function parseRgba(str) {
  const m = str.match(/rgba?\(([^)]+)\)/);
  if (!m) throw new Error(`not an rgba value: ${str}`);
  const p = m[1].split(",").map((s) => parseFloat(s.trim()));
  return [p[0], p[1], p[2], p.length > 3 ? p[3] : 1];
}

/** Composite a translucent colour over an opaque ground. */
function composite(rgbaStr, groundHex) {
  const [r, g, b, a] = parseRgba(rgbaStr);
  const [br, bg, bb] = parseHex(groundHex);
  return [a * r + (1 - a) * br, a * g + (1 - a) * bg, a * b + (1 - a) * bb];
}

function rgbToHslTriplet([r, g, b]) {
  const R = r / 255, G = g / 255, B = b / 255;
  const max = Math.max(R, G, B), min = Math.min(R, G, B);
  const l = (max + min) / 2;
  let h = 0, s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === R) h = ((G - B) / d + (G < B ? 6 : 0));
    else if (max === G) h = (B - R) / d + 2;
    else h = (R - G) / d + 4;
    h /= 6;
  }
  const r1 = (n, d = 1) => {
    const v = Math.round(n * 10 ** d) / 10 ** d;
    return Number.isInteger(v) ? String(v) : String(v);
  };
  return `${r1(h * 360)} ${r1(s * 100)}% ${r1(l * 100)}%`;
}

/* ── WCAG contrast, for the --check report ────────────────────────────── */

function relLuminance([r, g, b]) {
  const f = (c) => {
    const s = c / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}

function contrast(a, b) {
  const [l1, l2] = [relLuminance(a), relLuminance(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
}

/* ── emit ─────────────────────────────────────────────────────────────── */

function tokensFor(skin, mode) {
  const m = skin[mode];
  const out = {};

  for (const [k, v] of Object.entries(m.core)) out[k] = rgbToHslTriplet(parseHex(v));
  for (const [k, [v]] of Object.entries(m.alpha)) out[k] = rgbToHslTriplet(composite(v, m.ground));

  // Twelve family hues, retuned per skin so they carry the same identity
  // without fighting that skin's ground.
  const { s, l } = skin.cat;
  for (const [name, hue] of Object.entries(CAT_HUES)) out[`cat-${name}`] = `${hue} ${s}% ${l[mode]}%`;

  // The sidebar set trails the core so shadcn's sidebar primitives inherit
  // the skin instead of falling back to the default palette.
  out["sidebar-background"] = rgbToHslTriplet(parseHex(m.raw.rail));
  out["sidebar-foreground"] = out.foreground;
  out["sidebar-primary"] = out.primary;
  out["sidebar-primary-foreground"] = out["primary-foreground"];
  out["sidebar-accent"] = out.secondary;
  out["sidebar-accent-foreground"] = out["secondary-foreground"];
  out["sidebar-border"] = out.border;
  out["sidebar-ring"] = out.ring;

  return out;
}

function block(selector, skin, mode, { fonts }) {
  const t = tokensFor(skin, mode);
  const lines = [`${selector} {`];
  if (fonts) {
    lines.push(`  --font-display: ${skin.fonts.display};`);
    lines.push(`  --font-sans:    ${skin.fonts.sans};`);
    lines.push(`  --font-mono:    ${skin.fonts.mono};`);
    lines.push(`  --radius: ${skin.radius};`);
    lines.push("");
  }
  for (const [k, v] of Object.entries(t)) lines.push(`  --${k}: ${v};`);
  lines.push("");
  for (const [k, v] of Object.entries(skin[mode].raw)) lines.push(`  --${k}: ${v};`);
  lines.push("}");
  return lines.join("\n");
}

const parts = [
  `/* AUTO-GENERATED by scripts/build-skins.mjs — do not edit by hand.`,
  ` * Edit scripts/skin-palettes.mjs, then: node scripts/build-skins.mjs`,
  ` *`,
  ` * Three imported design themes, each with a full light and dark palette.`,
  ` * Applied as [data-skin] on <html>, crossed with the existing .dark class,`,
  ` * so mode and theme stay independent axes.`,
  ` */`,
  "",
];

for (const [id, skin] of Object.entries(SKINS)) {
  parts.push(`/* ══ ${skin.label} ═══════════════════════════════════════════ */`);
  parts.push(block(`[data-skin="${id}"]`, skin, "light", { fonts: true }));
  parts.push("");
  parts.push(block(`[data-skin="${id}"].dark`, skin, "dark", { fonts: false }));
  parts.push("");
}

const css = parts.join("\n");

/* ── contrast report ──────────────────────────────────────────────────── */

const PAIRS = [
  ["foreground", "background", 4.5],
  ["muted-foreground", "background", 4.5],
  ["muted-foreground", "card", 4.5],
  ["primary", "background", 3.0],
  ["accent", "background", 4.5],
  ["copper", "background", 4.5],
  ["destructive", "background", 4.5],
  ["primary-foreground", "primary", 4.5],
  ["accent-foreground", "accent", 4.5],
];

let failures = 0;
console.log("WCAG contrast check\n");
for (const [id, skin] of Object.entries(SKINS)) {
  for (const mode of ["light", "dark"]) {
    const m = skin[mode];
    const solid = (name) =>
      m.core[name] ? parseHex(m.core[name]) : composite(m.alpha[name][0], m.ground);
    const rows = PAIRS.map(([fg, bg, min]) => {
      const ratio = contrast(solid(fg), solid(bg));
      const ok = ratio >= min;
      if (!ok) failures++;
      return `    ${ok ? "pass" : "FAIL"}  ${ratio.toFixed(2).padStart(5)}:1  (min ${min})  ${fg} on ${bg}`;
    });
    console.log(`  ${skin.label} · ${mode}`);
    console.log(rows.join("\n"));
  }
  console.log("");
}
console.log(failures === 0 ? "All pairs pass." : `${failures} pair(s) below target.`);

if (!process.argv.includes("--check")) {
  writeFileSync(OUT, css + "\n", "utf8");
  console.log(`\nWrote ${OUT}`);
}
